[2025-02-02T21:11:12.747+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T21:11:12.770+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: batch_ingestion.generate_batch_data manual__2025-02-02T21:11:10.625897+00:00 [queued]>
[2025-02-02T21:11:12.785+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: batch_ingestion.generate_batch_data manual__2025-02-02T21:11:10.625897+00:00 [queued]>
[2025-02-02T21:11:12.787+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T21:11:12.805+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): generate_batch_data> on 2025-02-02 21:11:10.625897+00:00
[2025-02-02T21:11:12.820+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'batch_ingestion', 'generate_batch_data', 'manual__2025-02-02T21:11:10.625897+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/batch_ingestion.py', '--cfg-path', '/tmp/tmpxi7jwbpw']
[2025-02-02T21:11:12.824+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=196) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T21:11:12.824+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask generate_batch_data
[2025-02-02T21:11:12.825+0000] {standard_task_runner.py:72} INFO - Started process 198 to run task
[2025-02-02T21:11:12.910+0000] {task_command.py:467} INFO - Running <TaskInstance: batch_ingestion.generate_batch_data manual__2025-02-02T21:11:10.625897+00:00 [running]> on host eb32bd0cd201
[2025-02-02T21:11:13.082+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='batch_ingestion' AIRFLOW_CTX_TASK_ID='generate_batch_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T21:11:10.625897+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-02T21:11:10.625897+00:00'
[2025-02-02T21:11:13.085+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T21:11:13.199+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T21:11:13.212+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T21:11:13.213+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=batch_ingestion, task_id=generate_batch_data, run_id=manual__2025-02-02T21:11:10.625897+00:00, execution_date=20250202T211110, start_date=20250202T211112, end_date=20250202T211113
[2025-02-02T21:11:13.284+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T21:11:13.318+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T21:11:13.322+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
